### PR TITLE
Update before going live

### PR DESCRIPTION
**Pull request by nimbinatus**
fixing image directories and image links per deconst flags, updating landing page setup, and cleaning up the data for liquid templates

### CODE REVIEW

**Comment by catlook** [comment]
LGTM

**Comment by nimbinatus** [comment]
Wait, this needs to be reviewed by Keith, too

**Comment by catlook** [comment]
Either revert it or patch it with his revisions I guess.  Sorry, I jumped the gun.

-- Cat Lookabaugh, Sr. Information Developer
Rackspace Hosting – the #1 Managed Cloud Company
Info Dev Team      cat.lookabaugh@rackspace.com
Office: (210) 312-8193   Cell: (210) 364-1060

**Comment by nimbinatus** [comment]
It's ok; I should have put a WIP tag on it. My bad.

**Comment by nimbinatus** [comment]
@ktbartholomew gave it a +1, so it should be good to go

**Pull request merged**
